#!/bin/bash
echo "Exporting package list..."
sudo dpkg --get-selections > /home/will/SystemBackup/Package.list
echo "Backing up relevant /etc/ files..."
sudo cp -r /etc/apt/* /home/will/SystemBackup/etc/apt
sudo cp /etc/fstab /home/will/SystemBackup/etc
echo "Backing up GPG keys..."
sudo apt-key exportall > /home/will/SystemBackup/Repo.keys &> /dev/null
echo "Backing up dotfiles..."
sudo cp -r /home/will/.??* /home/will/SystemBackup/Dotfiles
