#!/bin/bash
echo "Exporting package list..."
sudo dpkg --get-selections > /home/will/SystemBackup/Package.list
echo "Backing up relevant /etc/ files..."
sudo rsync -rav --ignore-existing /etc/apt/ /home/will/SystemBackup/etc/apt/ >>/var/log/backups/backup.log 2>&1
sudo rsync -av /etc/fstab /home/will/SystemBackup/etc/ >> /var/log/backups/backup.log 2>&1
echo "Backing up GPG keys..."
sudo apt-key exportall > /home/will/SystemBackup/Repo.keys 
echo "Backing up dotfiles..."
sudo rsync -rav --ignore-existing /home/will/.??* /home/will/SystemBackup/Dotfiles >> /var/log/backups/backup.log 2>&1

echo "Syncing backups to remote Raspberry Pi..."
#sudo rsync -avzP --ignore-existing -e 'ssh -p 9000 -i /home/will/.ssh/id_rsa.pub' /home/will/SystemBackup/ pi@h0merouter.ddns.net:/media/USBHD/Backups/SystemBackup/ >> /var/log/backups/backup.log 2>&1
